export const metadata = {
    title: "LMS | About",
    description: "Generated by create next app",
  };
  
  function Layout({ children }) {
    return (
        <section>
            { children }
        </section>
    )
}

export default Layout;