import Link from "next/link";

export const metadata = {
    title: "LMS | Admin",
    description: "Generated by create next app",
  };
  

function Layout({ children }) {
    return (
        <section>
            <div className="parent">
            <div className="leftSide">
                <ul>
                    <li> <Link href={'/admin/personalInformation'}>User Profile</Link></li>
                    <li><Link href={'/admin/usrProducts'}>User Products</Link></li>
                </ul>
            </div>
            <div className="rightSide"> { children }</div>
            </div>
        </section>
    )
}

export default Layout;