export const metadata = {
    title: "LMS | Home",
    description: "Generated by create next app",
  };

  function Layout({ children }) {
    return (
        <section>
            { children }
        </section>
    )
}

export default Layout;